# Configurable properties
---

# Degree of polymerization(dp)
# Configure either single value (or) min_dp & max_dp for generating structures in a range of DP.
dp: 0      #0 to use the min and max range below
# (or)
min_dp: 3
max_dp: 5

# Experimental observation from NMR or other analysis on Bond precentages
bondconfig:  # Add in the percentage (%) values
  BO4: 60
  BB: 5
  B5: 10
  _4O5: 5
  _55: 5
  DBDO: 5

#### Please use either of S/G ratio or Monomer percentages. If both the values are given S/G ratio takes precedence

#### S/G ratio
s_g_ratio: 0       # set 0 for G type structures
                   # set to -1 to use the below S/G/H percentage values below
                   # set S/G ratio for SG type structures. Example : 1.8
# Monomer percentages : Experimental observation from NMR or other analysis on Monomer precentages
monoconfig:    # Add in the percentage(%) values
  G: 0          
  S: 0
  H: 0

# For individual lignin chains
png: true   # 2D structure  
matrices: true   # Adjacency and Connectivity Matrix
sdf: true   # *.mol or SDF file

# Json contains SMILES and evaluatied properties of the stuctures generated
json: true

# To update in MongoDBDatabase (optional)
addtoDB: false  #true, if mongodb instance is present
mongo_URI: 'mongodb://localhost:27017/admin?readPreference=primary&appname=MongoDB%20Compass&ssl=false'
mongo_dbname: 'lignindata'
mongo_collname: 'ligninstructs_Dec_6_test'
